// src/pages/Analytics.tsx
import React, { useState, useMemo } from 'react'
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
} from 'react-native'
import Svg, {
  Defs,
  LinearGradient,
  Stop,
  Path,
  Circle,
  Text as SvgText,
} from 'react-native-svg'
import { useDataStore } from '../stores/data'
import {
  totalMonthlySpend,
  projectedYearly,
  coffees,
  monthlyEquivalent,
} from '../utils/calculations'
import { buildSpendingTimeline, pointsToPath, RANGE_DAYS } from '../utils/chart'
import { useTheme } from '../context/ThemeContext'
import { theme, CURRENCY_SYMBOL } from '../theme'

export function Analytics() {
  const { colors } = useTheme()
  const store = useDataStore()

  const currency = store.settings.defaultCurrency ?? 'EUR'
  const symbol = CURRENCY_SYMBOL[currency] ?? ''

  const monthly = useMemo(() => totalMonthlySpend(store.subscriptions), [store.subscriptions])
  const yearly = useMemo(() => projectedYearly(store.subscriptions), [store.subscriptions])
  const coffeeCount = useMemo(() => coffees(monthly), [monthly])

  const breakdown = useMemo(
    () =>
      store.subscriptions
        .filter((s: any) => s.active !== false)
        .map((s: any) => ({ ...s, monthly: monthlyEquivalent(s.price, s.billingCycle) }))
        .sort((a: any, b: any) => b.monthly - a.monthly),
    [store.subscriptions]
  )

  const [timeRange, setTimeRange] = useState('1Y')
  const timeline = useMemo(
    () => buildSpendingTimeline(store.subscriptions, RANGE_DAYS[timeRange]),
    [store.subscriptions, timeRange]
  )
  const path = useMemo(() => pointsToPath(timeline, 300, 100), [timeline])

  return (
    <ScrollView
      style={[s.page, { backgroundColor: colors.bg }]}
      contentContainerStyle={s.content}
      showsVerticalScrollIndicator={false}
    >
      <Text style={[s.pageTitle, { color: colors.text }]}>Analytics</Text>

      {/* Summary */}
      <View style={[s.card, { backgroundColor: colors.surface }]}>
        <View style={s.summaryGrid}>
          <View style={s.stat}>
            <Text style={[s.statNum, { color: colors.text }]}>{symbol}{monthly.toFixed(0)}</Text>
            <Text style={[s.statLabel, { color: colors.textMuted }]}>per month</Text>
          </View>
          <View style={s.stat}>
            <Text style={[s.statNum, { color: colors.text }]}>{symbol}{yearly.toFixed(0)}</Text>
            <Text style={[s.statLabel, { color: colors.textMuted }]}>per year</Text>
          </View>
          <View style={s.stat}>
            <Text style={[s.statNum, { color: colors.text }]}>{coffeeCount}</Text>
            <Text style={[s.statLabel, { color: colors.textMuted }]}>coffees / mo</Text>
          </View>
        </View>
      </View>

      {/* Chart */}
      <View style={[s.card, { backgroundColor: colors.accent }]}>
        <View style={s.chartHeader}>
          <Text style={[s.cardTitle, { color: colors.accentFg }]}>Spending over time</Text>
          <View style={s.filters}>
            {Object.keys(RANGE_DAYS).map(f => (
              <TouchableOpacity
                key={f}
                style={[s.filterPill, {
                  backgroundColor: timeRange === f ? colors.accentFg : 'rgba(255,255,255,0.15)',
                }]}
                onPress={() => setTimeRange(f)}
                accessibilityRole="button"
              >
                <Text style={[s.filterPillText, {
                  color: timeRange === f ? colors.accent : colors.accentFg,
                }]}>{f}</Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        <Svg width="100%" height={100} viewBox="0 0 300 100" preserveAspectRatio="none">
          <Defs>
            <LinearGradient id="g-analytics" x1="0" y1="0" x2="0" y2="1">
              <Stop offset="0%" stopColor={colors.accentFg} stopOpacity={0.25} />
              <Stop offset="100%" stopColor={colors.accentFg} stopOpacity={0} />
            </LinearGradient>
          </Defs>
          {store.subscriptions.length > 0 ? (
            <>
              <Path d={path.area} fill="url(#g-analytics)" />
              <Path d={path.line} fill="none" stroke={colors.accentFg} strokeWidth={1.5} strokeLinejoin="round" />
              <Circle cx={path.last.x} cy={path.last.y} r={3} fill={colors.accentFg} />
            </>
          ) : (
            <SvgText x={150} y={54} textAnchor="middle" fontSize={12} fill={colors.accentFg} opacity={0.6}>
              Add a subscription to see the chart
            </SvgText>
          )}
        </Svg>
      </View>

      {/* Breakdown */}
      {breakdown.length > 0 ? (
        <View style={[s.card, { backgroundColor: colors.surface }]}>
          <Text style={[s.cardTitle, { color: colors.text, marginBottom: theme.sp5 }]}>Breakdown</Text>
          {breakdown.map((sub: any) => {
            const pct = monthly > 0 ? (sub.monthly / monthly) * 100 : 0
            return (
              <View key={sub.id} style={s.breakdownRow}>
                <View style={s.breakdownInfo}>
                  <Text style={[s.breakdownName, { color: colors.text }]}>{sub.emoji ?? '💳'} {sub.name}</Text>
                  <Text style={[s.breakdownPct, { color: colors.textMuted }]}>{symbol}{sub.monthly.toFixed(2)} · {pct.toFixed(0)}%</Text>
                </View>
                <View style={[s.barTrack, { backgroundColor: colors.surfaceHigh }]}>
                  <View style={[s.barFill, { flex: pct, maxWidth: `${pct}%` as any, backgroundColor: colors.accent }]} />
                  <View style={{ flex: 100 - pct }} />
                </View>
              </View>
            )
          })}
        </View>
      ) : (
        <View style={[s.card, s.emptyCard, { backgroundColor: colors.surface }]}>
          <Text style={[s.empty, { color: colors.textFaint }]}>No subscriptions yet</Text>
        </View>
      )}
    </ScrollView>
  )
}

const s = StyleSheet.create({
  page: { flex: 1 },
  content: { padding: theme.sp4, gap: theme.sp4, paddingBottom: 110 },

  pageTitle: {
    fontSize: 34,
    fontFamily: theme.fontBlack,
    letterSpacing: -1,
    marginBottom: theme.sp4,
  },

  card: {
    borderRadius: theme.radiusXl,
    padding: theme.sp5,
    ...theme.shadow,
  },

  summaryGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: theme.sp3 },
  stat: { flex: 1 },
  statNum: { fontSize: theme.textXl, fontFamily: theme.fontMonoBold },
  statLabel: { fontSize: theme.textXs, fontFamily: theme.fontRegular, marginTop: 2 },

  chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: theme.sp4, flexWrap: 'wrap', gap: theme.sp2 },
  cardTitle: { fontSize: theme.textBase, fontFamily: theme.fontBold },

  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.sp2 },
  filterPill: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: 20 },
  filterPillText: { fontSize: theme.textXs, fontFamily: theme.fontMedium },

  breakdownRow: { marginBottom: theme.sp4 },
  breakdownInfo: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: theme.sp1 },
  breakdownName: { fontSize: theme.textSm, fontFamily: theme.fontMedium },
  breakdownPct: { fontSize: theme.textSm, fontFamily: theme.fontRegular },
  barTrack: { height: 4, borderRadius: 2, overflow: 'hidden', flexDirection: 'row' },
  barFill: { height: 4 },

  emptyCard: { alignItems: 'center', padding: theme.sp8 },
  empty: { fontSize: theme.textSm, fontFamily: theme.fontRegular },
})

// src/pages/Analytics.svelte
<script>
  import { subscriptions, settings } from '../stores/data.svelte.js'
  import { totalMonthlySpend, projectedYearly, coffees, monthlyEquivalent } from '../utils/calculations.js'
  import { buildSpendingTimeline, pointsToPath, RANGE_DAYS } from '../utils/chart.js'
  import { fade } from 'svelte/transition'
  import { tweened } from 'svelte/motion'
  import { cubicOut } from 'svelte/easing'

  const currency = $derived(settings.value.defaultCurrency ?? 'EUR')
  const symbol   = $derived({ EUR: '€', USD: '$', GBP: '£', BRL: 'R$' }[currency] ?? '')

  const monthly     = $derived(totalMonthlySpend(subscriptions.items))
  const yearly      = $derived(projectedYearly(subscriptions.items))
  const coffeeCount = $derived(coffees(monthly))

  const breakdown = $derived(
    subscriptions.items
      .filter(s => s.active !== false)
      .map(s => ({ ...s, monthly: monthlyEquivalent(s.price, s.billingCycle) }))
      .sort((a, b) => b.monthly - a.monthly)
  )

  let timeRange  = $state('1Y')
  const timeline = $derived(buildSpendingTimeline(subscriptions.items, RANGE_DAYS[timeRange]))
  const path     = $derived(pointsToPath(timeline, 300, 100))

  // Animated counters
  const monthlyAnim = tweened(0, { duration: 600, easing: cubicOut })
  const yearlyAnim  = tweened(0, { duration: 600, easing: cubicOut })
  const coffeeAnim  = tweened(0, { duration: 600, easing: cubicOut })
  $effect(() => { monthlyAnim.set(monthly) })
  $effect(() => { yearlyAnim.set(yearly) })
  $effect(() => { coffeeAnim.set(coffeeCount) })
</script>

<div class="analytics-page">
  <!-- Summary -->
  <div class="card">
    <div class="summary-grid">
      <div class="stat">
        <p class="stat-num">{symbol}{$monthlyAnim.toFixed(0)}</p>
        <p class="stat-label">per month</p>
      </div>
      <div class="stat">
        <p class="stat-num">{symbol}{$yearlyAnim.toFixed(0)}</p>
        <p class="stat-label">per year</p>
      </div>
      <div class="stat">
        <p class="stat-num">{$coffeeAnim.toFixed(0)}</p>
        <p class="stat-label">coffees / mo</p>
      </div>
    </div>
  </div>

  <!-- Chart -->
  <div class="card">
    <div class="chart-header">
      <p class="card-title">Spending over time</p>
      <div class="filters">
        {#each Object.keys(RANGE_DAYS) as f}
          <button
            class="filter-pill"
            class:active={timeRange === f}
            aria-pressed={timeRange === f}
            onclick={() => timeRange = f}
          >{f}</button>
        {/each}
      </div>
    </div>
    <svg class="chart" viewBox="0 0 300 100" preserveAspectRatio="none" aria-hidden="true">
      <defs>
        <linearGradient id="g2" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stop-color="#000" stop-opacity="0.14"/>
          <stop offset="100%" stop-color="#000" stop-opacity="0"/>
        </linearGradient>
      </defs>
      {#if subscriptions.items.length > 0}
        <path d={path.area} fill="url(#g2)" />
        <path d={path.line} fill="none" stroke="#000" stroke-width="1.5" stroke-linejoin="round"/>
        <circle cx={path.last.x} cy={path.last.y} r="3" fill="#000"/>
      {:else}
        <text x="150" y="54" text-anchor="middle" font-size="12" fill="#888">Add a subscription to see the chart</text>
      {/if}
    </svg>
  </div>

  <!-- Breakdown -->
  {#if breakdown.length > 0}
    <div class="card">
      <p class="card-title" style="margin-bottom: var(--space-5)">Breakdown</p>
      {#each breakdown as sub, i (sub.id)}
        {@const pct = monthly > 0 ? (sub.monthly / monthly) * 100 : 0}
        <div class="breakdown-row" in:fade={{ duration: 240, delay: 60 + i * 50 }}>
          <div class="breakdown-info">
            <span class="breakdown-name">{sub.emoji ?? '💳'} {sub.name}</span>
            <span class="breakdown-pct">{symbol}{sub.monthly.toFixed(2)} · {pct.toFixed(0)}%</span>
          </div>
          <div class="bar-track">
            <div class="bar-fill" style="--target: {pct}%; animation-delay: {60 + i * 50}ms"></div>
          </div>
        </div>
      {/each}
    </div>
  {:else}
    <div class="card empty-card">
      <p class="empty">No subscriptions yet</p>
    </div>
  {/if}
</div>

<style>
  .analytics-page { display: flex; flex-direction: column; gap: var(--space-4); padding-bottom: var(--space-6); }

  .card {
    background: var(--color-surface);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow-card);
    padding: var(--space-5);
    transition: transform 200ms ease, box-shadow 200ms ease;
  }
  .card:hover { transform: translateY(-2px); box-shadow: 0 6px 16px rgba(0,0,0,0.08); }

  .summary-grid { display: flex; justify-content: space-between; gap: var(--space-3); }
  .stat-num { font-size: var(--text-xl); font-weight: 800; font-variant-numeric: tabular-nums; }
  .stat-label { font-size: var(--text-xs); color: var(--color-text-muted); margin-top: 2px; }

  .chart-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: var(--space-4); flex-wrap: wrap; gap: var(--space-2); }
  .card-title { font-size: var(--text-base); font-weight: 700; }
  .chart { width: 100%; height: 100px; display: block; }

  .filters { display: flex; gap: var(--space-2); flex-wrap: wrap; }
  .filter-pill {
    padding: 5px 12px; border-radius: 20px;
    background: var(--color-bg); font-size: var(--text-xs); font-weight: 600;
    transition: background 200ms ease, color 200ms ease;
  }
  .filter-pill.active { background: var(--color-accent); color: var(--color-accent-fg); }

  .breakdown-row { margin-bottom: var(--space-4); }
  .breakdown-info { display: flex; justify-content: space-between; margin-bottom: var(--space-1); }
  .breakdown-name { font-size: var(--text-sm); font-weight: 500; }
  .breakdown-pct { font-size: var(--text-sm); color: var(--color-text-muted); font-variant-numeric: tabular-nums; }
  .bar-track { height: 4px; background: var(--color-border); border-radius: 2px; overflow: hidden; }

  .bar-fill {
    height: 100%; background: var(--color-accent); border-radius: 2px;
    width: 0;
    animation: bar-grow 600ms cubic-bezier(0.22, 0.61, 0.36, 1) forwards;
  }

  @keyframes bar-grow {
    from { width: 0; }
    to   { width: var(--target); }
  }

  .empty-card { text-align: center; padding: var(--space-8); }
  .empty { font-size: var(--text-sm); color: var(--color-text-muted); }
</style>
