// src/components/forms/AddTrackForm.svelte
<script>
  let { onSubmit, onCancel } = $props()

  let type         = $state('subscription')
  let name         = $state('')
  let emoji        = $state('💳')
  let price        = $state('')
  let currency     = $state('EUR')
  let billingCycle = $state('monthly')
  let nextDate     = $state('')
  let category     = $state('Other')
  let payment      = $state('Card')
  let note         = $state('')

  const types    = ['subscription', 'app', 'event']
  const currencies = ['EUR', 'USD', 'GBP', 'BRL']
  const cycles   = ['weekly', 'monthly', 'yearly']
  const cats     = ['Streaming', 'Music', 'Gaming', 'Cloud', 'Productivity', 'News', 'Fitness', 'Education', 'Other']
  const payments = ['Card', 'PayPal', 'Apple Pay', 'Google Pay', 'Bank Transfer', 'Other']

  function submit(e) {
    e.preventDefault()
    if (!name.trim() || !price || !nextDate) return
    onSubmit({
      type,
      name: name.trim(),
      emoji,
      color: '#000000',
      price: parseFloat(price),
      currency,
      billingCycle,
      nextChargeDate: nextDate,
      purchaseDate: nextDate,
      date: nextDate,
      category,
      paymentMethod: payment,
      note: note.trim(),
      active: true,
    })
  }
</script>

<form onsubmit={submit}>
  <div class="type-tabs">
    {#each types as t}
      <button type="button" class="tab" class:active={type === t} onclick={() => type = t}>
        {t.charAt(0).toUpperCase() + t.slice(1)}
      </button>
    {/each}
  </div>

  <div class="fields">
    <div class="row">
      <div class="field emoji-field">
        <label>Icon</label>
        <input type="text" bind:value={emoji} maxlength="2" />
      </div>
      <div class="field grow">
        <label>Name *</label>
        <input type="text" bind:value={name} placeholder="Netflix" required />
      </div>
    </div>

    <div class="row">
      <div class="field grow">
        <label>Price *</label>
        <input type="number" bind:value={price} min="0" step="0.01" placeholder="9.99" required />
      </div>
      <div class="field">
        <label>Currency</label>
        <select bind:value={currency}>
          {#each currencies as c}<option>{c}</option>{/each}
        </select>
      </div>
    </div>

    {#if type === 'subscription'}
      <div class="field">
        <label>Billing cycle</label>
        <div class="pills">
          {#each cycles as c}
            <button type="button" class="pill" class:active={billingCycle === c} onclick={() => billingCycle = c}>
              {c}
            </button>
          {/each}
        </div>
      </div>
    {/if}

    <div class="field">
      <label>{type === 'event' ? 'Date' : type === 'app' ? 'Purchase date' : 'Next charge'} *</label>
      <input type="date" bind:value={nextDate} required />
    </div>

    <div class="row">
      <div class="field grow">
        <label>Category</label>
        <select bind:value={category}>
          {#each cats as c}<option>{c}</option>{/each}
        </select>
      </div>
      {#if type === 'subscription'}
        <div class="field grow">
          <label>Payment</label>
          <select bind:value={payment}>
            {#each payments as m}<option>{m}</option>{/each}
          </select>
        </div>
      {/if}
    </div>

    <div class="field">
      <label>Note</label>
      <input type="text" bind:value={note} placeholder="Optional" />
    </div>
  </div>

  <div class="actions">
    <button type="button" class="btn-secondary" onclick={onCancel}>Cancel</button>
    <button type="submit" class="btn-primary">Add</button>
  </div>
</form>

<style>
  .type-tabs { display: flex; gap: var(--space-2); margin-bottom: var(--space-5); }
  .tab {
    flex: 1; padding: var(--space-2) 0; border-radius: var(--radius-md);
    font-size: var(--text-sm); font-weight: 600;
    background: var(--color-bg); color: var(--color-text-muted);
    transition: background 150ms, color 150ms;
  }
  .tab.active { background: var(--color-accent); color: var(--color-accent-fg); }

  .fields { display: flex; flex-direction: column; gap: var(--space-4); }

  .row { display: flex; gap: var(--space-3); align-items: flex-end; }
  .field { display: flex; flex-direction: column; gap: var(--space-1); }
  .field.grow { flex: 1; }
  .field.emoji-field { width: 60px; }

  label { font-size: var(--text-xs); font-weight: 600; color: var(--color-text-muted); text-transform: uppercase; letter-spacing: 0.04em; }

  input, select {
    padding: var(--space-3) var(--space-3);
    border: 1.5px solid var(--color-border);
    border-radius: var(--radius-md);
    font-size: var(--text-sm);
    background: var(--color-bg);
    width: 100%;
    transition: border-color 150ms;
  }
  input:focus, select:focus { outline: none; border-color: var(--color-accent); }

  .field.emoji-field input { text-align: center; font-size: 18px; padding: var(--space-2); }

  .pills { display: flex; gap: var(--space-2); }
  .pill {
    flex: 1; padding: var(--space-2) 0; border-radius: var(--radius-md);
    font-size: var(--text-xs); font-weight: 600;
    background: var(--color-bg); color: var(--color-text-muted);
    border: 1.5px solid var(--color-border);
    transition: all 150ms;
  }
  .pill.active { background: var(--color-accent); color: var(--color-accent-fg); border-color: var(--color-accent); }

  .actions { display: flex; gap: var(--space-3); margin-top: var(--space-6); }
  .btn-primary {
    flex: 1; padding: var(--space-3) 0; border-radius: var(--radius-md);
    background: var(--color-accent); color: var(--color-accent-fg);
    font-size: var(--text-sm); font-weight: 700;
  }
  .btn-secondary {
    padding: var(--space-3) var(--space-5); border-radius: var(--radius-md);
    background: var(--color-bg); color: var(--color-text-muted);
    font-size: var(--text-sm); font-weight: 600;
  }
</style>

// src/components/forms/AddTrackForm.tsx
import React, { useState } from 'react'
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
} from 'react-native'
import { Picker } from '@react-native-picker/picker'
import { theme } from '../../theme'

const TYPES = ['subscription', 'app', 'event'] as const
const CURRENCIES = ['EUR', 'USD', 'GBP', 'BRL']
const CYCLES = ['weekly', 'monthly', 'yearly']
const CATEGORIES = ['Streaming', 'Music', 'Gaming', 'Cloud', 'Productivity', 'News', 'Fitness', 'Education', 'Other']
const PAYMENTS = ['Card', 'PayPal', 'Apple Pay', 'Google Pay', 'Bank Transfer', 'Other']

interface Props {
  onSubmit: (data: any) => void
  onCancel: () => void
}

export function AddTrackForm({ onSubmit, onCancel }: Props) {
  const [type, setType] = useState<typeof TYPES[number]>('subscription')
  const [name, setName] = useState('')
  const [emoji, setEmoji] = useState('💳')
  const [price, setPrice] = useState('')
  const [currency, setCurrency] = useState('EUR')
  const [billingCycle, setBillingCycle] = useState('monthly')
  const [nextDate, setNextDate] = useState('')
  const [category, setCategory] = useState('Other')
  const [payment, setPayment] = useState('Card')
  const [note, setNote] = useState('')

  function submit() {
    if (!name.trim() || !price || !nextDate) return
    onSubmit({
      type,
      name: name.trim(),
      emoji,
      color: '#000000',
      price: parseFloat(price),
      currency,
      billingCycle,
      nextChargeDate: nextDate,
      purchaseDate: nextDate,
      date: nextDate,
      category,
      paymentMethod: payment,
      note: note.trim(),
      active: true,
    })
  }

  const dateLabel = type === 'event' ? 'Date' : type === 'app' ? 'Purchase date' : 'Next charge'

  return (
    <View>
      <View style={s.typeTabs}>
        {TYPES.map(t => (
          <TouchableOpacity
            key={t}
            style={[s.tab, type === t && s.tabActive]}
            onPress={() => setType(t)}
          >
            <Text style={[s.tabText, type === t && s.tabTextActive]}>
              {t.charAt(0).toUpperCase() + t.slice(1)}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <View style={s.fields}>
        <View style={s.row}>
          <View style={s.emojiField}>
            <Text style={s.label}>Icon</Text>
            <TextInput
              style={[s.input, s.emojiInput]}
              value={emoji}
              onChangeText={setEmoji}
              maxLength={2}
            />
          </View>
          <View style={s.grow}>
            <Text style={s.label}>Name *</Text>
            <TextInput
              style={s.input}
              value={name}
              onChangeText={setName}
              placeholder="Netflix"
            />
          </View>
        </View>

        <View style={s.row}>
          <View style={s.grow}>
            <Text style={s.label}>Price *</Text>
            <TextInput
              style={s.input}
              value={price}
              onChangeText={setPrice}
              placeholder="9.99"
              keyboardType="decimal-pad"
            />
          </View>
          <View style={s.pickerWrap}>
            <Text style={s.label}>Currency</Text>
            <Picker
              selectedValue={currency}
              onValueChange={setCurrency}
              style={s.picker}
            >
              {CURRENCIES.map(c => <Picker.Item key={c} label={c} value={c} />)}
            </Picker>
          </View>
        </View>

        {type === 'subscription' && (
          <View>
            <Text style={s.label}>Billing cycle</Text>
            <View style={s.pills}>
              {CYCLES.map(c => (
                <TouchableOpacity
                  key={c}
                  style={[s.pill, billingCycle === c && s.pillActive]}
                  onPress={() => setBillingCycle(c)}
                >
                  <Text style={[s.pillText, billingCycle === c && s.pillTextActive]}>{c}</Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>
        )}

        <View>
          <Text style={s.label}>{dateLabel} * (YYYY-MM-DD)</Text>
          <TextInput
            style={s.input}
            value={nextDate}
            onChangeText={setNextDate}
            placeholder="2025-12-31"
            keyboardType="numeric"
          />
        </View>

        <View style={s.row}>
          <View style={s.grow}>
            <Text style={s.label}>Category</Text>
            <Picker
              selectedValue={category}
              onValueChange={setCategory}
              style={s.picker}
            >
              {CATEGORIES.map(c => <Picker.Item key={c} label={c} value={c} />)}
            </Picker>
          </View>
          {type === 'subscription' && (
            <View style={s.grow}>
              <Text style={s.label}>Payment</Text>
              <Picker
                selectedValue={payment}
                onValueChange={setPayment}
                style={s.picker}
              >
                {PAYMENTS.map(m => <Picker.Item key={m} label={m} value={m} />)}
              </Picker>
            </View>
          )}
        </View>

        <View>
          <Text style={s.label}>Note</Text>
          <TextInput
            style={s.input}
            value={note}
            onChangeText={setNote}
            placeholder="Optional"
          />
        </View>
      </View>

      <View style={s.actions}>
        <TouchableOpacity style={s.btnSecondary} onPress={onCancel}>
          <Text style={s.btnSecondaryText}>Cancel</Text>
        </TouchableOpacity>
        <TouchableOpacity style={s.btnPrimary} onPress={submit}>
          <Text style={s.btnPrimaryText}>Add</Text>
        </TouchableOpacity>
      </View>
    </View>
  )
}

const s = StyleSheet.create({
  typeTabs: {
    flexDirection: 'row',
    gap: theme.sp2,
    marginBottom: theme.sp5,
  },
  tab: {
    flex: 1,
    paddingVertical: theme.sp2,
    borderRadius: theme.radiusMd,
    backgroundColor: theme.bg,
    alignItems: 'center',
  },
  tabActive: { backgroundColor: theme.accent },
  tabText: { fontSize: theme.textSm, fontWeight: '600', color: theme.textMuted },
  tabTextActive: { color: theme.accentFg },

  fields: { gap: theme.sp4 },
  row: { flexDirection: 'row', gap: theme.sp3, alignItems: 'flex-end' },
  grow: { flex: 1 },

  label: {
    fontSize: theme.textXs,
    fontWeight: '600',
    color: theme.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: theme.sp1,
  },
  input: {
    paddingHorizontal: theme.sp3,
    paddingVertical: theme.sp3,
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: theme.radiusMd,
    fontSize: theme.textSm,
    backgroundColor: theme.bg,
    color: theme.text,
  },
  emojiField: { width: 64 },
  emojiInput: { textAlign: 'center', fontSize: 18 },

  pickerWrap: { flex: 1 },
  picker: {
    backgroundColor: theme.bg,
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: theme.radiusMd,
    height: 44,
  },

  pills: { flexDirection: 'row', gap: theme.sp2 },
  pill: {
    flex: 1,
    paddingVertical: theme.sp2,
    borderRadius: theme.radiusMd,
    backgroundColor: theme.bg,
    borderWidth: 1.5,
    borderColor: theme.border,
    alignItems: 'center',
  },
  pillActive: { backgroundColor: theme.accent, borderColor: theme.accent },
  pillText: { fontSize: theme.textXs, fontWeight: '600', color: theme.textMuted },
  pillTextActive: { color: theme.accentFg },

  actions: { flexDirection: 'row', gap: theme.sp3, marginTop: theme.sp6 },
  btnPrimary: {
    flex: 1,
    paddingVertical: theme.sp3,
    borderRadius: theme.radiusMd,
    backgroundColor: theme.accent,
    alignItems: 'center',
  },
  btnPrimaryText: { fontSize: theme.textSm, fontWeight: '700', color: theme.accentFg },
  btnSecondary: {
    paddingVertical: theme.sp3,
    paddingHorizontal: theme.sp5,
    borderRadius: theme.radiusMd,
    backgroundColor: theme.bg,
    alignItems: 'center',
  },
  btnSecondaryText: { fontSize: theme.textSm, fontWeight: '600', color: theme.textMuted },
})
